export enum ENV {
    PORT = 'PORT',
    JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
    JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
    BUCKET_URL = 'BUCKET_URL',
    BUCKET_ACCESS_KEY = 'BUCKET_ACCESS_KEY',
    BUCKET_SECRET_KEY = 'BUCKET_SECRET_KEY',
}
